name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["RoPieee/RoPieee"]
assignees:
  - spockfish
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2025.08 (Default)
        - 2025.06.1
        - 2025.06
        - 2025.05
        - 2025.04
        - 2025.02
        - 2025.01
      default: 0
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      description: Which hardware are you using?
      options:
        - Raspberry Pi 5
        - Raspberry Pi 5 Compute Module
        - Raspberry Pi 4
        - Raspberry Pi 4 Compute Module
        - Raspberry Pi 3
        - Raspberry Pi 3 Compute Module
        - Raspberry Pi Zero 2 W
        - Allo Usbridge (Signature)
      default: 0
    validations:
      required: true
  - type: input
    id: feedback
    attributes:
      label: RoPieee Feedback ID
      description: Please provide the Feedback ID, if you sent any
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Additional information
      description: Provide additional information, if you think this helps in any way.
      render: shell
      
